CREATE TABLE IF NOT EXISTS courses (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    university VARCHAR(200) NOT NULL DEFAULT 'UnB',
    created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE disciplines
    ADD COLUMN IF NOT EXISTS course_id INTEGER REFERENCES courses(id) ON DELETE SET NULL;